//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bank Management SystemUntitled
//  @ File Name : ACCOUNT.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class ACCOUNT
{
	public Object NUMBER;
	public Object BALANCE;
	public void DEPOSIT()
	{
	
	}
	
	public void WITHDRAW()
	{
	
	}
}
