//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ANIMAL.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class ANIMAL
{
	public Object AGE;
	public void IS MAMMAL()
	{
	
	}
}
