//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bank Management SystemUntitled
//  @ File Name : ATM TRANSACTIONS.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class ATM TRANSACTIONS
{
	public Object TRANSACTION ID;
	public Object DATE;
	public Object TYPE;
	public Object AMOUNT;
	public void MODIFIES()
	{
	
	}
}
