//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bank Management SystemUntitled
//  @ File Name : ATM.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class ATM
{
	public Object LOCATION;
	public Object MANAGED BY;
	public void TRANSACTIONS()
	{
	
	}
}
