//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bank Management System
//  @ File Name : BANK.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class BANK
{
	public Object CODE;
	public Object ADDRESS;
	public void MANAGES()
	{
	
	}
}
