//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SHAPESUntitled
//  @ File Name : CIRCLE.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class CIRCLE extends SHAPE
{
	private Object RADIUS;
	public void AREA()
	{
	
	}
	
	public void CIRCLE()
	{
	
	}
	
	public void GET RADIUS()
	{
	
	}
	
	public void PERIMETER()
	{
	
	}
	
	public void SET RADIUS()
	{
	
	}
}
