//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Bank Management SystemUntitled
//  @ File Name : CUSTOMER.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class CUSTOMER
{
	public Object NAME;
	public Object ADDRESS;
	public Object DOB;
	public Object CARD NUMBER;
	public Object PIN;
	public void VERIFY PASSWORD()
	{
	
	}
}
