//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : FISH.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class FISH
{
	private Object SIZE IN FEET;
	private void SWIM()
	{
	
	}
}
