//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SHAPESUntitled
//  @ File Name : RECTANGLE.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class RECTANGLE extends SHAPE
{
	private Object HEIGHT;
	private Object WIDTH;
	public void AREA()
	{
	
	}
	
	public void GET HEIGHT()
	{
	
	}
	
	public void GET WIDTH()
	{
	
	}
	
	public void PERIMETER()
	{
	
	}
	
	public void RECTANGLE()
	{
	
	}
	
	public void SET HEIGHT()
	{
	
	}
	
	public void SET WIDTH()
	{
	
	}
}
