//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : SHAPESUntitled
//  @ File Name : SHAPE.java
//  @ Date : 3/24/2020
//  @ Author : MIRZA MUZAMMIL ALI BAIG
//
//




public class SHAPE
{
	private Object COLOR;
	private Object ORIGIN;
	public void AREA()
	{
	
	}
	
	public void GET COLOR()
	{
	
	}
	
	public void GET ORIGIN()
	{
	
	}
	
	public void PERIMETER()
	{
	
	}
	
	public void SHAPE()
	{
	
	}
}
