//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ZEBRA.java
//  @ Date : 3/24/2020
//  @ Author : 
//
//




public class ZEBRA
{
	public Object IS_WILD;
	public void RUN()
	{
	
	}
}
